version: '3.8'

services:
  linkedin-mcp:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - linkedin_profiles:/app/data/linkedin_profiles
    environment:
      - HEADLESS=true
      - HOST=0.0.0.0
      - PORT=8080
    env_file:
      - .env
    restart: unless-stopped

volumes:
  linkedin_profiles:
    driver: local